package com.AndrewMaasCarpentry;

public enum ItemType {
    GENERAL_CONDITIONS, EXISTING_CONDITIONS, MASONRY, METALS, WOODS_PLASTICS_COMPOSITES,
    THERMAL_AND_MOISTURE, OPENINGS, FINISHES, FURNISHING, PLUMBING, HVAC, ELECTRICAL,
    PROFIT_AND_OVERHEAD, INSURANCE,CHANGE_ORDER
}
